### PR TITLE
Optional udt fields

### PR DESCRIPTION
**Pull request by cparker92**
This change should allow devs to specify whether or not they care about their udt class missing a field that is present in the live schema.

### CODE REVIEW

**Comment by doanduyhai** [comment]
Instead of focusing on UDT fields, why not introduce a global option `achilles.validate.schema` = true/false ?

It would solve your problem and also relax the constraint of schema validation for other people as well

**Comment by cparker92** [comment]
How about both?

**Comment by doanduyhai** [comment]
Not both

`achilles.ddl.ignore.missing.udt.fields` is only a particular instance of a more general case `achilles.validate.schema` so it's better to implement the general case

**Comment by cparker92** [comment]
Sounds good

**Pull request merged**
